services:
  postgres-db:
    image: postgres:15
    container_name: postgres-monitor
    environment:
      POSTGRES_DB: monitordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456  # ← SENHA SUPER SIMPLES
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitor-network
    # ADICIONE ESTA LINHA para forçar a senha
    command: postgres -c log_statement=all

  monitor-app:
    build: .
    container_name: monitor-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/monitordb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha123
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - monitor-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  monitor-network:
    driver: bridge