version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres-db:
    image: postgres:15
    container_name: postgres-monitor
    environment:
      POSTGRES_DB: monitordb
      POSTGRES_USER: RM554460
      POSTGRES_PASSWORD: fiap100786
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitor-network

  # Aplicação Spring Boot
  monitor-app:
    build: .
    container_name: monitor-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/monitordb
      SPRING_DATASOURCE_USERNAME: RM554460
      SPRING_DATASOURCE_PASSWORD: fiap100786
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - monitor-network
    restart: unless-stopped

# Volumes para persistência de dados
volumes:
  postgres_data:

# Rede para comunicação entre containers
networks:
  monitor-network:
    driver: bridge