# docker-compose.yml ATUALIZADO (REMOVA a linha version)
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-fiap.postgres.database.azure.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=fiap
      - SPRING_DATASOURCE_PASSWORD=SuaSenha123!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - db
    networks:
      - monitor-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=monitor_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
        - "5433:5432"  # Mude para 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitor-network

volumes:
  postgres_data:

networks:
  monitor-network:
    driver: bridge