name: CI/CD with PostgreSQL and Docker

on:
  push:
    branches: [ main, develop ]

env:
  IMAGE_NAME: medicao-api

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: monitor_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build application
        run: |
          echo "🔨 Building application..."
          mvn clean compile
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/monitor_db
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password123

      - name: Run tests
        run: |
          echo "🧪 Running tests..."
          mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/monitor_db
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password123

      - name: Build JAR package
        run: |
          echo "📦 Building JAR..."
          mvn clean package -DskipTests

      - name: Verify JAR file
        run: |
          echo "🔍 Verifying JAR..."
          ls -la target/
          find target/ -name "*.jar" -type f

      - name: Build Docker image
        run: |
          echo "🐳 Building Docker image..."
          docker build -t $IMAGE_NAME:$GITHUB_SHA .

      - name: Run container integration test
        run: |
          echo "🚀 Running container tests..."
          docker run -d --name test-db \
            -e POSTGRES_DB=monitor_db \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=password123 \
            -p 5433:5432 \
            postgres:13
          
          sleep 20
          echo "📊 PostgreSQL container started..."
          
          docker run -d \
            --name test-api \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/monitor_db \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=password123 \
            -p 8080:8080 \
            $IMAGE_NAME:$GITHUB_SHA
          
          sleep 30
          echo "🔌 Testing API connection..."
          
          curl -f http://localhost:8080/api/medicoes || exit 1
          
          docker stop test-api test-db
          docker rm test-api test-db
          echo "✅ Container tests passed!"

  debug-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub Context
        run: |
          echo "🔍 GITHUB CONTEXT:"
          echo "Ref: '${{ github.ref }}'"
          echo "Is main: ${{ github.ref == 'refs/heads/main' }}"
          echo "Is develop: ${{ github.ref == 'refs/heads/develop' }}"

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build-and-test, debug-context]
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Deploy to Staging
        run: |
          echo "📦 Deploying to STAGING environment"

  deploy-production:
    runs-on: ubuntu-latest
    needs: [build-and-test, debug-context]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production
        run: |
          echo "🎯 Deploying to PRODUCTION environment"