name: CI/CD with PostgreSQL and Docker

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: monitor_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5433:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # ✅ DEBUG: Testar conexão PostgreSQL
      - name: Test PostgreSQL connection
        run: |
          sudo apt-get install -y postgresql-client
          echo "Aguardando PostgreSQL..."
          sleep 10
          pg_isready -h localhost -p 5433 -U postgres || echo "PostgreSQL ainda não está pronto"
          sleep 5
          pg_isready -h localhost -p 5433 -U postgres

      - name: Build with Maven
        run: mvn clean package -DskipTests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/monitor_db
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password123

      - name: Build Docker image
        run: |
          docker build -t monitor-app:$GITHUB_SHA .
          docker images

      # ✅ CORREÇÃO: Usar network do Docker para conectar containers
      - name: Test Docker container with network
        run: |
          # Criar network customizada
          docker network create test-network
          
          # Conectar o PostgreSQL à network
          docker network connect test-network postgres
          
          # Rodar a aplicação na MESMA network
          docker run -d --name test-app --network test-network \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/monitor_db \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=password123 \
            -p 8080:8080 \
            monitor-app:$GITHUB_SHA
          
          echo "Aguardando aplicação iniciar..."
          sleep 45  # ✅ Aumentar tempo de espera
          
          # Teste de saúde
          echo "Testando health check..."
          curl -f http://localhost:8080/actuator/health || \
          (echo "❌ Health check falhou - verificando logs..." && docker logs test-app && exit 1)
          
          echo "✅ Aplicação está respondendo!"

      - name: Logs on failure
        if: failure()
        run: |
          echo "=== LOGS DA APLICAÇÃO ==="
          docker logs test-app || echo "Container da aplicação não encontrado"
          echo "=== CONTAINERS ATIVOS ==="
          docker ps -a
          echo "=== NETWORKS ==="
          docker network ls
          echo "=== POSTGRES LOGS ==="
          docker logs postgres || echo "Container PostgreSQL não encontrado"

      - name: Cleanup
        if: always()
        run: |
          docker stop test-app || true
          docker rm test-app || true
          docker network rm test-network || true